spring:
    frontUrl: "${FRONT_URL}"
    files:
        location: ${FILES_LOCATION}
        upload_path: "${UPLOAD_PATH}"
    application:
        name: Register
    config:
        import: "optional:file:.env[.properties]"
    datasource:
        username: "${DB_USERNAME}"
        password: "${DB_PASSWORD}"
        url: "${DB_URL}"
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: "${AUTH_AUTHORITY}"
    jpa:
        hibernate:
            naming:
                physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
        show-sql: true
