AGS=1
BC=1
BCS=1
CAM=1
#COA=1
COL=1
CHP=1
CHH=1
CDMX=1
DUR=1
GTO=1
GRO=1
HGO=1
JAL=1
MEX=1
MIC=1
MOR=1
NAY=1
NL=10
OAX=1
PUE=1
QRO=1
ROO=1
SLP=1
SIN=1
SON=1
TAB=1
TAM=1
TLA=1
VER=1
YUC=1
ZAC=1
VIT=1
ARARM=1
UNAM=1
IPN=1
