INSERT INTO db_register.C_ESTADO (IDESTADO,ABREVIADO,NOMBRE) VALUES
	 (1,'AGS','AGUASCALIENTES'),
	 (2,'BC','BAJA CALIFORNIA'),
	 (3,'BCS','BAJA CALIFORNIA SUR'),
	 (4,'CAM','CAMPECHE'),
	 (5,'COA','COAHUILA'),
	 (6,'COL','COLIMA'),
	 (7,'CHP','CHIAPAS'),
	 (8,'CHH','CHIHUAHUA'),
	 (9,'CDMX','CIUDAD DE MÉXICO'),
	 (10,'DUR','DURANGO');
INSERT INTO db_register.C_ESTADO (IDESTADO,ABREVIADO,NOMBRE) VALUES
	 (11,'GTO','GUANAJUATO'),
	 (12,'GRO','GUERRERO'),
	 (13,'HGO','HIDALGO'),
	 (14,'JAL','JALISCO'),
	 (15,'MEX','ESTADO DE MÉXICO'),
	 (16,'MIC','MICHOACÁN'),
	 (17,'MOR','MORELOS'),
	 (18,'NAY','NAYARIT'),
	 (19,'NL','NUEVO LEÓN'),
	 (20,'OAX','OAXACA');
INSERT INTO db_register.C_ESTADO (IDESTADO,ABREVIADO,NOMBRE) VALUES
	 (21,'PUE','PUEBLA'),
	 (22,'QRO','QUERÉTARO'),
	 (23,'ROO','QUINTANA ROO'),
	 (24,'SLP','SAN LUIS POTOSÍ'),
	 (25,'SIN','SINALOA'),
	 (26,'SON','SONORA'),
	 (27,'TAB','TABASCO'),
	 (28,'TAM','TAMAULIPAS'),
	 (29,'TLA','TLAXCALA'),
	 (30,'VER','VERACRUZ');
INSERT INTO db_register.C_ESTADO (IDESTADO,ABREVIADO,NOMBRE) VALUES
	 (31,'YUC','YUCATÁN'),
	 (32,'ZAC','ZACATECAS');
